name: "Docs"
on:
  push:
    branches:
      - docs
jobs:
  test:
    name: Deploy docs site
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v2
            
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      - name: npm install
        run: npm i
            
      - name: build
        run: npm run build
        env:
          DOCS_BUCKET: ${{ secrets.DOCS_BUCKET }}
      
      - name: deploy
        run: npm run deploy
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DOCS_KEY_ID }}
          AWS_REGION: ${{ secrets.DOCS_REGION }}
          DOCS_BUCKET: ${{ secrets.DOCS_BUCKET }}
